/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_uart.h"
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "fsl_port.h"
#include "fsl_dspi.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define UART_1_PERIPHERAL UART1
/* Definition of the clock source frequency */
#define UART_1_CLOCK_SOURCE CLOCK_GetFreq(UART1_CLK_SRC)

/* Definitions for BOARD_InitBUTTONsPeripheral functional group */
/* Alias for GPIOC peripheral */
#define BOARD_SW2_GPIO GPIOC
/* Alias for PORTC */
#define BOARD_SW2_PORT PORTC
/* SW2 interrupt vector ID (number). */
#define BOARD_SW2_IRQN PORTC_IRQn
/* SW2 interrupt handler identifier. */
#define BOARD_SW2_IRQHANDLER PORTC_IRQHandler
/* Alias for GPIOB peripheral */
#define BOARD_SW3_GPIO GPIOB
/* Alias for PORTB */
#define BOARD_SW3_PORT PORTB
/* SW3 interrupt vector ID (number). */
#define BOARD_SW3_IRQN PORTB_IRQn
/* SW3 interrupt handler identifier. */
#define BOARD_SW3_IRQHANDLER PORTB_IRQHandler

/* Definitions for BOARD_InitLEDsPeripheral functional group */
/* Alias for GPIOD peripheral */
#define BOARD_LEDRGB_BLUE_GPIO GPIOD
/* Alias for GPIOA peripheral */
#define BOARD_LEDRGB_RED_GREEN_GPIO GPIOA

/* Definitions for BOARD_InitDEBUG_UARTPeripheral functional group */
/* Definition of peripheral ID */
#define BOARD_DEBUG_UART_PERIPHERAL UART1
/* Definition of the clock source frequency */
#define BOARD_DEBUG_UART_CLOCK_SOURCE CLOCK_GetFreq(UART1_CLK_SRC)

/* Definitions for BOARD_InitSDHCPeripheral functional group */
/* Alias for GPIOB peripheral */
#define BOARD_SDHC_DETECT_GPIO GPIOB
/* BOARD_InitSDHCPeripheral defines for SPI0 */
/* Definition of peripheral ID */
#define BOARD_SDHC_PERIPHERAL SPI0
/* Definition of the clock source */
#define BOARD_SDHC_CLOCK_SOURCE DSPI0_CLK_SRC
/* Definition of the clock source frequency */
#define BOARD_SDHC_CLK_FREQ CLOCK_GetFreq(BOARD_SDHC_CLOCK_SOURCE)

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const uart_config_t UART_1_config;
extern const uart_config_t BOARD_DEBUG_UART_config;
extern const dspi_master_config_t BOARD_SDHC_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);
void BOARD_InitBUTTONsPeripheral(void);
void BOARD_InitLEDsPeripheral(void);
void BOARD_InitDEBUG_UARTPeripheral(void);
void BOARD_InitACCELPeripheral(void);
void BOARD_InitSDHCPeripheral(void);
void BOARD_InitPOTPeripheral(void);
void BOARD_InitLSENSEPeripheral(void);
void BOARD_InitWIFIPeripheral(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
